#!/usr/bin/env bash
# new-analysis.sh — stamp a reproducible analysis skeleton.
# Standard: _docs/analysis-structure.md. Run inside your `analyses/` repo.
#
# Usage:   new-analysis.sh <slug> [--author NAME] [--question "..."]
#          new-analysis.sh --selftest
# Creates: ./<yyyy-mm-dd>-<slug>/  (tree + provenance README + run.sh + gitignore)

set -euo pipefail

die() { printf 'new-analysis: %s\n' "$*" >&2; exit 1; }

scaffold() {
    local root="$1" slug="$2" author="$3" question="$4"
    local date dir
    date="$(date +%F)"
    dir="$root/${date}-${slug}"
    [ -e "$dir" ] && die "already exists: $dir"

    mkdir -p "$dir"/{sql,src,notebooks,data/raw,data/interim,outputs}

    cat > "$dir/README.md" <<EOF
---
question:   "${question}"
author:     ${author}
date:       ${date}
as_of:      ${date}          # data snapshot date — set to the real extract date
sources:    []               # e.g. [iris.golden.orders@v3]
metrics:    []               # e.g. [gross_margin@metric-tree v2] — cite versions
git_sha:                     # commit that produced outputs/
decisions:                   # human judgment as explicit params, not prose
  cohort:   ""
  excluded: ""
  window:   ""
  rejected: ""               # alternatives considered and killed, + why (stops re-litigation)
fingerprint:                 # the reproducibility anchor (not raw data)
  rows:
  checksum:
  headline: {}
findings:   ""               # 3-line answer once known
---

# ${slug}

**Question.** ${question}

## Findings

_TBD — fill \`findings\` above and expand here._

## Reproduce

\`\`\`bash
./run.sh
\`\`\`

## Files

- \`sql/\`   — every query, named + parametrized (\`:as_of\`)
- \`src/\`   — logic (notebooks import from here, never define)
- \`outputs/\` — regenerated by run.sh; no data dumps
EOF

    cat > "$dir/run.sh" <<'EOF'
#!/usr/bin/env bash
# Regenerate outputs from raw → done. Must run clean to count as reproducible.
set -euo pipefail
cd "$(dirname "$0")"

# 1. extract — run every query in sql/ into data/raw/, parametrized by :as_of
#    (pulled from the README provenance header).
# ponytail: assumes psql + $DATABASE_URL. Swap the psql line for your client.
as_of="$(awk '/^as_of:/{print $2; exit}' README.md)"
shopt -s nullglob
for q in sql/*.sql; do
  out="data/raw/$(basename "${q%.sql}").csv"
  echo "extract: $q -> $out (as_of=${as_of})"
  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -v as_of="$as_of" --csv -f "$q" > "$out"
done
shopt -u nullglob

# 2. transform/analyze (src/)
# 3. write outputs/

# tie-out: recompute the headline and fail on drift vs README fingerprint.headline
# python3 src/tie_out.py || { echo "TIE-OUT FAILED: headline != fingerprint"; exit 1; }
EOF
    chmod +x "$dir/run.sh"

    # PII/secrets boundary: never commit row-level data. Outputs stay tracked.
    cat > "$dir/.gitignore" <<'EOF'
data/
!data/.gitkeep
*.env
EOF
    touch "$dir/data/.gitkeep"
    : > "$dir/requirements.txt"

    printf '%s\n' "$dir"
}

if [ "${1:-}" = "--selftest" ]; then
    tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
    out="$(scaffold "$tmp" probe "tester" "does it work?")"
    for p in README.md run.sh .gitignore sql src notebooks data/raw data/interim outputs; do
        [ -e "$out/$p" ] || die "selftest: missing $p"
    done
    [ -x "$out/run.sh" ] || die "selftest: run.sh not executable"
    grep -q '^data/$' "$out/.gitignore" || die "selftest: data/ not gitignored (PII boundary)"
    grep -q '^question:' "$out/README.md" || die "selftest: no provenance header"
    echo "selftest OK"; exit 0
fi

[ $# -ge 1 ] || die "usage: new-analysis.sh <slug> [--author NAME] [--question \"...\"]"
slug="$1"; shift
author="${USER:-unknown}"; question="TODO"
while [ $# -gt 0 ]; do
    case "$1" in
        --author)   author="${2:?}"; shift 2 ;;
        --question) question="${2:?}"; shift 2 ;;
        *) die "unknown arg: $1" ;;
    esac
done
[[ "$slug" =~ ^[a-z0-9-]+$ ]] || die "slug must be lowercase-kebab: got '$slug'"

dir="$(scaffold "." "$slug" "$author" "$question")"
echo "created $dir"
echo "next: fill the provenance header, drop queries in sql/, wire run.sh + tie-out."
