#!/usr/bin/env bash
# skills-index.sh — regenerate the skill catalog from each SKILL.md frontmatter.
# (Stolen from openwiki's thesis: generate docs from source, don't hand-maintain.
#  Minus openwiki — no LLM needed, it's just awk over frontmatter you already have.)
#
#   skills-index.sh            # print index to stdout
#   skills-index.sh --write    # write _docs/skills-index.md
#   skills-index.sh --check    # exit 1 if the committed file is stale (for lint/CI)
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd -P)"
root="$(dirname "$here")" # skills dir = parent of _docs
out="$here/skills-index.md"

generate() {
    echo "# Skills index"
    echo
    echo "_Generated by \`_docs/skills-index.sh\` — do not edit by hand. Run with \`--write\` to refresh._"
    echo
    for f in "$root"/*/SKILL.md; do
        [ -e "$f" ] || continue
        awk '
            /^---[[:space:]]*$/ { fm++; next }
            fm==1 && /^name:/ { sub(/^name:[[:space:]]*/,""); name=$0 }
            fm==1 && /^description:/ {
                sub(/^description:[[:space:]]*/,""); d=$0
                gsub(/^"|"$/,"",d)
                if (d ~ /^[>|][+-]?$/ || d=="") { collect=1; desc="" } else { collect=0; desc=d }
                next
            }
            fm==1 && collect==1 {
                if ($0 ~ /^[a-zA-Z_]+:/) { collect=0 }
                else { line=$0; sub(/^[[:space:]]+/,"",line); desc=desc (desc==""?"":" ") line }
            }
            fm==2 && name!="" {
                gsub(/\|/," ",desc)
                if (length(desc)>140) desc=substr(desc,1,137) "..."
                printf "- **%s** — %s\n", name, desc
                exit
            }
        ' "$f"
    done
}

case "${1:-}" in
    --write)
        generate >"$out"
        echo "wrote $out" >&2
        ;;
    --check)
        if ! diff -q <(generate) "$out" >/dev/null 2>&1; then
            echo "skills-index.md is stale — run: _docs/skills-index.sh --write" >&2
            exit 1
        fi
        echo "skills-index.md up to date" >&2
        ;;
    "") generate ;;
    *)
        echo "usage: skills-index.sh [--write|--check]" >&2
        exit 2
        ;;
esac
