name: Secret Scan
description: Run gitleaks secret scanning
inputs:
  config:
    description: Path to gitleaks config file
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITLEAKS_CONFIG: ${{ inputs.config }}
